apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: financial-dashboard

resources:
  - namespace.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-configmap.yaml
  - ingress.yaml
  - frontend-hpa.yaml
  - backend-hpa.yaml
  - network-policy.yaml
  - service-account.yaml
