apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: financial-dashboard
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: financial-api
  namespace: financial-dashboard
automountServiceAccountToken: false
